version: "3.9"
services:
  webpacker:
    build: .
    command: bash -c "rm -rf /harvest_helper/public/packs; /harvest_helper/bin/webpack-dev-server"
    volumes:
      - .:/harvest_helper
    ports:
      - "3035:3035"
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/harvest_helper
    ports:
      - "3000:3000"
    depends_on:
      - webpacker
      - db